base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('loginr/', views.loginr, name="loginr"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="registerUser"),
    
    path('test/', views.tests, name="tests"),
    path('',views.home, name="home"),
    path('room/<str:pk>/', views.room, name="room"),
    path('userprofile/<str:pk>/', views.userprofile, name="userprofile"),
    path('web/', views.web),
    path('createroom/', views.createroom, name="createroom"),
    path('updateroom/<str:pk>/', views.updateroom, name="updateroom"),
    path('deleteroom/<str:pk>/', views.deleteroom, name="deleteroom"),
    path('contact/', views.contact, name="contact")


]

studyapp/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
   
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here. sure!
# class Message(models.Model):
#     room
class Topic(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Contact(models.Model):
    sender=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    c_email=models.EmailField(null=False)
    c_message=models.TextField(null=True)
    c_send_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.c_message)
    

class Rooms(models.Model):
    host=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic=models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=200)
    description=models.TextField(null=True,blank=True)
    # participants=
    updated=models.DateTimeField(auto_now=True) # time stamp crepated everytime it is saved 
    created=models.DateTimeField(auto_now_add=True) ##time stamp created at the first time
    
    class Meta:
        ordering=['-updated','-created']
    def __str__(self):
        return str(self.name)

    
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey('Rooms', on_delete=models.SET_NULL, null=True)
    body = models.TextField(null=True)
    updated=models.DateTimeField(auto_now=True)  
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering=['-updated','-created']
    def __str__(self):
        return str(self.body)
    

templates/act.html
{%  block content %}
<br>
<hr>

<h3 class="text-center text1">Activity feed</h3>
{% for message in message %}
<!-- <small>@{{message.user}} -<small>{{message.created|timesince }}, ago </small> </small>
<p>{{message.body}}</p>
<p>{{message.room}}</p>
<hr> -->
<div class="d-flex justify-content-center py-2">
    <div class="second py-2 px-2"> <span class="text1">BOX: {{message.room}}<br> "{{message.body}}"</span>
        <div class="d-flex justify-content-between py-1 pt-2">
            <div><span class="text2">@{{message.user}}</span></div>
            <div><span class="text3">{{message.created|timesince }}, ago</span></div>
        </div>
    </div>
</div>

{% endfor %}

    

    

{% endblock %}

templates/contact.html
{% extends 'main.html' %}
{% block content %}
<h1>hello</h1>
<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us
        directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form  name="contact" action="" method="POST">
              {% csrf_token %}
                 <div class="row">

                   
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="email"  name="c_email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
               

                </div>
               
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text"  name="c_message" rows="2"
                                class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->
                <input type="submit" value="submit" />

            </form>

           
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>San Francisco, CA 94126, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@mdbootstrap.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->
{% endblock %}

templates/delete.html
{% extends 'main.html' %}
{% block content %}
<form method="POST" action="">

    {% csrf_token %}
    <p>Are you sure you want to delete the "{{obj}}" ? </p><hr>
    <a href="{{request.META.HTTP_REFERER}}">GO Back</a><br><br><br>
    <input type="submit" value="confirm"/>
</form>

{% endblock %}

templates/feed.html
{% block content %}
{% for l in mylist %}

<div class="card bg-transparent ">
    <a  href="/userprofile/{{l.host.id}}">
        <h5 class="card-header text1">Featured <span class="text2">@{{l.host.username}}</span></h5>
    </a>
    <div class="card-body">
        <a href="/room/{{l.id}}">
            <h5 class="card-title text1">BOX name: <span class="text4"> {{l.name}} <span/></h5>
        </a>
        <p class="card-text text1">topic: {{l.topic}}</p>
        {% if request.user == l.host %}
        <a href="{% url 'updateroom' l.id %}" class="btn btn-primary">update</a>
        <a href="{% url 'deleteroom' l.id %}" class="btn btn-danger">Delete</a>
        {% endif %}
        <br>

    </div>

</div>
{% endfor %}
{% endblock %}

templates/home.html
{% extends 'main.html' %}

{% block content %}
<style>
    



</style>

<div class="container">
    <br>
    <br>
    <div class="row"> 
        
        <div class="col-sm">
        
    {% include 'topics.html' %}
        </div>
       
        
   


  <div class="col-sm-5 vl">
       <div>
        <a href="{% url 'createroom' %}"><button type="button" class="btn btn-info"><h4>CREATE ROOM</h4></button></a>
        
        <hr>
        {% include 'feed.html' %}
        <!-- {% for l in mylist %}
        <div class="card bg-dark text-white">
           <a href="/userprofile/{{l.host.id}}"> <h5 class="card-header">Featured @{{l.host.username}}</h5></a>
            <div class="card-body">
                <a href="/room/{{l.id}}"><h5 class="card-title">{{l.id}}--{{l.name}}</h5></a>
                <p class="card-text">topic:{{l.topic}}</p>
                {% if request.user == l.host %}
                <a href="{% url 'updateroom' l.id %}" class="btn btn-primary">update</a>
                <a href="{% url 'deleteroom' l.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
                <br>
        
            </div>
            
        </div>
        {% endfor %} -->
        </div>
        </div>
        <!-- activity feed -->
        <div class="col-sm vl">
         
            {% include 'act.html' %}
        </div>

       
        














        
        <!-- <br>
        <br>
        
        {% for l in mylist %}
        <h4><a href="{% url 'updateroom' l.id %}">EDIT</a></h4>
        <h5><a href="{% url 'deleteroom' l.id %}">DELETE</a></h5>
        <span>@{{l.host.username}}</span>
       <a href="/room/{{l.id}}"> <h3>{{l.id}} </a>--{{l.name}}</h3>
       <br>
       <small>topic:{{l.topic}}</small>
       <hr>

        {% endfor %} -->
      
   
</div>
</div>
{% endblock %}

templates/loginr.html
{% extends 'main.html' %}
{% block content %}
<!-- login page -->


{% if page == 'login' %}
<div class="login-box">
   <h2>Login</h2>
   <form method="POST" action="">
      {% csrf_token %}
      <div class="user-box">
       
         <input type="text" name="username"  required />
         <label>Username</label>
         
      </div>
      <div class="user-box">
         <label>Password</label>
         <input type="password" name="password"  required />
        
      </div>
      <a href="#">
         <span></span>
         <span></span>
         <span></span>
         <span></span>
         <input type="submit" value="login" />
      </a>
      <p>havent sign up ?</p>
      <a href="{% url 'registerUser' %}"><button>sign up</button></a>
      
   </form>
</div>
<!-- <div>
<form method="POST" action="">
   {% csrf_token %}
   USERNAME<input type="text" name="username" placeholder="username" required/><br>
   PASSWORD<input type="password" name="password" placeholder="password" required/><br>
   <input type="submit" value="login" />
   
</form>
</div> -->
<!-- <p>havent sign up ?</p>
<a href="{% url 'registerUser' %}"><button>sign up</button></a> -->
<!-- register page -->
{% else %}
<!-- <div class="login-box">
   <h2>Register</h2>
   <form method="POST" action="">
      {% csrf_token %}
      <div class="user-box">
         {{form.as_p}}

         
      </div>
      
      </div>
      <a href="#">
         <span></span>
         <span></span>
         <span></span>
         <span></span>
         <input type="submit" value="Register" />
      </a>
   <p>already signed up?
   <p>
      <a href="{% url 'loginr' %}"><button>LOGIN</button></a>

   </form>
</div> -->

<div>
   <form method="POST" action="">
      {% csrf_token %}
      {{form.as_p}}

      
      <input type="submit" value="Register" />
    

   </form>
</div>
<p>already signed up?
<p>
   <a href="{% url 'loginr' %}"><button>LOGIN</button></a>

{% endif %}




{% endblock %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudyApp</title>
  
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
    <link rel="stylesheet" type="text/css"  href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/css/mdb.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/js/mdb.min.js"></script>
<!-- <style>
    
</style> -->
    </head>

<body class="">
    {% include 'navbar.html' %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    

    {% block content %}
    



    {% endblock %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>

<script src="{% static 'js/main.js' %}"></script>

   
    
</body>
</html>

templates/navbar.html
{% block content %}
<!-- <nav class="navbar navbar-dark" style="background-color: #0dcaf0; ">
    <a href="{% url 'home' %}" class="navbar-brand cus">Helix</a>
   {% if request.user.is_authenticated %}
   <a href="{% url 'logout' %}" class="">LOGOUT  {{user}}</a>

   
    {% else %}
    <a href="{% url 'loginr' %}" class="">LOGIN</a>
    {% endif %}
    <form class="form-inline gus" method="GET" action="{% url 'home' %}">
        <input class="form-control mr-sm-2 " type="text" name="q" placeholder="Search..."" aria-label="Search">
        
    </form>
</nav> -->
<nav class="mb-4 navbar navbar-expand-lg navbar-dark" style="background-color: #0dcaf0;">
    <a class="navbar-brand font-bold cus" href="{% url 'home' %}">Helix</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
        aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSuapportedContent-4">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contact' %}"><i class="fa fa-envelope"></i> Contact <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-gear"></i> Settings</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{user}} </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownMenuLink-4">
                    
                    
                    <a class="dropdown-item" href="/userprofile/{{user.id}}">My account</a>
                    {% if request.user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                    
                    <a class="dropdown-item" href="{% url 'loginr' %}">LOGIN</a>
                    {% endif %}

                    
                </div>
            </li>
        </ul>
        <form class="form-inline " method="GET" action="{% url 'home' %}">
            <input class="form-control mr-sm-2 gus" type="text" name="q" placeholder="Search..."" aria-label=" Search">
        
        </form>
    </div>
</nav>

{% endblock %}


<!-- <nav>
    <h1 style="color: blue;">company logo</h1>
    <h3><a href="{% url 'loginr' %}">LOGIN</a></h3>
</nav> -->
<!-- <form method="GET" action="{% url 'home' %}">
    <input type="text" name="q" placeholder="Search...">

    <!-- <a href="#" class="search-btn">
                <i class="fas fa-search"></i> -->
    <!-- </a> -->
<!-- </form> --> 

templates/room.html
{% extends 'main.html' %}

{% block content %}

<h1>boxes</h1>
<div class="card bg-dark text-white" style="width: 30rem;">
    <div class="card-body">
        <h5 class="card-title">{{room}}</h5>
        <p class="card-text">{{desc}}</p>
        </div>
        </div>
        <h3>Chat box</h3>
        {% for conv in conv %}
       
        
            <div class="row">
                <div class="col-sm-7">
                    <div class="widget panel">
                        <div class="panel-body">
                           
                                <i class="fa fa-twitter text-info pull-right"></i>
                            </h4>
                            <hr>
                            <ul class="list-table">
                                <li style="width:70px;">
                                    <img class="img-circle img-bordered-primary"
                                        src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="" width="65px"
                                        height="65px">
                                </li>
                                <li class="text-left">
                                    <h5 class="semibold ellipsis nm">{{conv.user}}</h5>
                                    <p class="text-muted nm">5k followers</p>
                                </li>
                                <li class="text-right">
                                    <button type="button" class="btn btn-sm btn-success">Follow</button>
                                </li>
                            </ul>
                        </div>
        
                        <ul class="list-group">
                            <li class="list-group-item">
                                <p class="nm">{{conv}}</p>
                                <small class="text-muted">{{conv.created|timesince }}, ago</small>
        
                        </ul>
                    </div>
                </div>
        
        
        
            </div>
            </div>
        
        {% endfor %}
        {% if request.user.is_authenticated %}
        <br>
        <div class="input-group row ">
            <div class="col-sm-5 " style="margin-left: 20px;">
            <form method="POST" action="">
                {% csrf_token %}
                <!-- <input type="text" required/> -->
                <input type="text" name="body" placeholder="your messages here" class="form-control border border-info"
                    aria-label="Default" aria-describedby="inputGroup-sizing-default">

            </form>
            </div>

        </div>
        {% endif %}
      

        



 



{% endblock %}

templates/room_form.html
{% extends 'main.html' %}

{% block content %}
<div>
    <h1>Room input</h1>
    <form method="POST" action="" >
        {% csrf_token %} 
        {{form.as_p}}
        
        <input type="submit" value="submit"/>
        

    </form>
</div>


{% endblock %}

templates/test.html
{% block content %}
<div>

    <h4>
       {% for x in my %}
        {{ x }}
        <br>
       {% endfor %}

    
       
       

    
    </h4>
</div>


{% endblock %}

templates/test1.html
{% extends 'main.html' %}

{% block content %}



{% endblock %}

templates/topics.html
{% block content %}
<h3 >browse topics </h3>

<hr>
<ul class="list-unstyled ">
    <a href="{% url 'home' %}"><li class="text4">ALL <span class="pull-right text2">{{topic.count}}</span></li></a>
{% for e in topic %}

<a href="{% url 'home' %}?q={{e.name}}">
    <li class="text4">{{e}} <span class="pull-right text2">{{e.rooms_set.all.count}}</span></li>
</a>
<!-- <h4><a href="{% url 'home' %}?q={{e.name}}">{{e}}</a></h4> -->

{% endfor %}
</ul>


{% endblock %}

templates/userprofile.html
{% extends 'main.html' %}
{% block content %}

<div class="container">
    <h1 class="text4"> USER NAME: {{user.username}}</h1>
    <h3 class="text4"> NO of rooms @{{user.username}} created:  {{count}}</h3>
    <div class="row">
        <div class="col-sm">
            {% include 'topics.html' %}

        </div>
        <div class="col-sm-5">
           
            {% include 'feed.html' %}
        </div>
        <div class="col-sm">
          
            {% include 'act.html' %}
        </div>
    </div>
</div>

{% endblock %}